# Site settings
title: Signal.js
email: carloandreaconte@icloud.com
description: > # this means to ignore newlines until "baseurl:"
    Playing with signals to power javascript animations.
baseurl: "/Signal.js" # the subpath of your site, e.g. /blog/
url: "http://mrgreenh.github.io" # the base hostname & protocol for your site
twitter_username: mrgreenh
github_username:  mrgreenh

# Build settings
markdown: kramdown
exclude: [src, signal_editor/src, node_modules, dist, gulpfile.js, package.json, README.md, Gemfile, Gemfile.lock]
gems:
  - octopress-markdown-tag
